/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidadejemplo.Vistas;

import java.util.HashSet;
import javax.swing.JOptionPane;
import universidadejemplo.AccesoaDatos.MateriaData;
import universidadejemplo.Entidades.Materia;

/**
 *
 * @author Pc
 */
public class VistaMenuMateria extends javax.swing.JInternalFrame {
    private MateriaData mate = new MateriaData();
    private Materia materia = null;
    /**
     * Creates new form VistaMenuMateria
     */
    public VistaMenuMateria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jAgregar = new javax.swing.JButton();
        jEliminar = new javax.swing.JButton();
        jActualizar = new javax.swing.JButton();
        jSalirMa = new javax.swing.JButton();
        jBuscar = new javax.swing.JButton();
        jcodi = new javax.swing.JTextField();
        jNombre = new javax.swing.JTextField();
        jAño = new javax.swing.JTextField();
        jBoolean = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(0, 102, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setText("Materia");

        jLabel2.setText("Codigo:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Año:");

        jLabel5.setText("Estado:");

        jAgregar.setText("Nuevo");
        jAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAgregarActionPerformed(evt);
            }
        });

        jEliminar.setText("Eliminar");
        jEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEliminarActionPerformed(evt);
            }
        });

        jActualizar.setText("Guardar");
        jActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jActualizarActionPerformed(evt);
            }
        });

        jSalirMa.setText("Salir");
        jSalirMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalirMaActionPerformed(evt);
            }
        });

        jBuscar.setText("Buscar");
        jBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuscarActionPerformed(evt);
            }
        });

        jcodi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcodiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jAgregar))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBoolean)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jEliminar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jAño))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jActualizar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jSalirMa))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jcodi)
                                        .addComponent(jNombre))
                                    .addGap(23, 23, 23)
                                    .addComponent(jBuscar))))))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBuscar)
                        .addComponent(jcodi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jBoolean))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAgregar)
                    .addComponent(jEliminar)
                    .addComponent(jActualizar)
                    .addComponent(jSalirMa))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSalirMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalirMaActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jSalirMaActionPerformed

    private void jBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscarActionPerformed
        // TODO add your handling code here:
         try{
        Integer cod=Integer.parseInt(jcodi.getText());
        jAgregar.setEnabled(false);
        Materia mat = mate.buscarMateria(cod);
        if(mat!=null){ 
            jNombre.setText(mat.getNombre());
            jAño.setText(mat.getAnioMateria()+"");                    
            jBoolean.setSelected(mat.isActivo());            
            }   
        
        }catch(NumberFormatException nf){
          JOptionPane.showMessageDialog(this, "Debe ingresar un codigo valido");
        
        }
    }//GEN-LAST:event_jBuscarActionPerformed

    private void jActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jActualizarActionPerformed
        try{
             
             Integer cod=Integer.parseInt(jcodi.getText());
             String nombre=jNombre.getText();
             int año =Integer.parseInt(jAño.getText());
             if (nombre.isEmpty()|| año==0){
                 JOptionPane.showMessageDialog(this, "No debe entrar campos vacios");
                 return;
              }
             Boolean estado=jBoolean.isSelected();
     
           if (materia==null){
               
               materia=new Materia(cod, nombre, año, estado);
               mate.modificarMateria(materia);
               limpiarDatos();
               jAgregar.setEnabled(true);
           }else{
              materia.setIdMateria(cod);
              materia.setNombre(nombre);
              materia.setAnioMateria(año);
              materia.setActivo(estado);
               
              
              mate.modificarMateria(materia); 
              limpiarDatos();
          
           }
        }catch(NumberFormatException nf){
          JOptionPane.showMessageDialog(this, "Debe ingresar un codigo valido");
        }
    }//GEN-LAST:event_jActualizarActionPerformed

    private void jAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAgregarActionPerformed
        if (jNombre.getText().isEmpty()|| jAño.getText().isEmpty() ){
             
           JOptionPane.showInternalMessageDialog(this, "los campos no deben estas vaciosssssssss");  
           return; 
         }  
         
         String nom=jNombre.getText();
         int anno= Integer.parseInt(jAño.getText());
         if(!(jBoolean.isSelected())){
         JOptionPane.showMessageDialog(this, "Debe activar el estado de la materia");
         }else{
         boolean boton = jBoolean.isSelected();
         
         materia.setNombre(nom);
         materia.setAnioMateria(anno);
         materia.setActivo(boton);
            
         mate.guardarMateria(materia);
         
         limpiarDatos();
         
         }
    }//GEN-LAST:event_jAgregarActionPerformed

    private void jEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEliminarActionPerformed
        if(materia!=null){
        mate.eliminarMateria(materia.getIdMateria());
        materia=null;
        limpiarDatos();
         jAgregar.setEnabled(true);    
        }else{
       JOptionPane.showMessageDialog(this, "No hay materia seleccionada");
       }
    }//GEN-LAST:event_jEliminarActionPerformed

    private void jcodiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcodiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcodiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jActualizar;
    private javax.swing.JButton jAgregar;
    private javax.swing.JTextField jAño;
    private javax.swing.JRadioButton jBoolean;
    private javax.swing.JButton jBuscar;
    private javax.swing.JButton jEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jNombre;
    private javax.swing.JButton jSalirMa;
    private javax.swing.JTextField jcodi;
    // End of variables declaration//GEN-END:variables

    private void limpiarDatos(){

  jNombre.setText("");
  jAño.setText("");
  jBoolean.setSelected(false);
  jcodi.setText("");
}
}
